In [7]:
"""
Q1

Write a function my_checker_board(n), where the output m is an n×n

array with the following form:
m=[1 0 1 0 1
   0 1 0 1 0
   1 0 1 0 1
   0 1 0 1 0
   1 0 1 0 1]

Note that the upper-left element should always be 1. Assume that n is a strictly positive integer.
"""

import numpy as np
def my_checker_board(n):
  l = []
  m = n*n
  for i in range(0,n**2):
    if(i%2==0):
      l.append(1)
    else:
      l.append(0)
  A = np.array(l)
  return(A.reshape(n,n))


In [8]:
print(my_checker_board(7))

[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


In [9]:
"""
Q2
Write a function my_cylinder(r,h), where r and h are the radius and height of a cylinder, respectively, 
and the output is a list [s, v] where s and v are the surface area and volume of the same cylinder, respectively. 
"""
def my_cylinder(r,h):
  s = 2*np.pi*r**2 + 2*np.pi*r*h
  v = np.pi*r**2*h
  return [s,v]

In [10]:
s,v = my_cylinder(1,5)
print(f"The surface area is {s} and volume is {v}")

The surface area is 37.69911184307752 and volume is 15.707963267948966


In [11]:
"""
Q2
Write a function my_split_matrix(m), where m is an array, 
the output is a list [m1, m2] where m1 is the left half of m, and m2 is the right half of m. 
In the case where there is an odd number of columns, the middle column should go to m1. 
Assume that m has at least two columns.
"""

def my_split_matrix(m):
  p, q = m.shape
  if(q%2==0):
    m1 = m[:,0:q/2]
    m2 = m[:,q/2:]
  else:
    m1 = m[:,0:q//2 +1]
    m2 = m[:,q//2 +1:]
  return [m1,m2]


In [12]:
m = np.ones((7,7))
m1, m2 = my_split_matrix(m)
print(f"The 1st block m1 is {m1} and 2nd block m2 is {m2}")

The 1st block m1 is [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] and 2nd block m2 is [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
A = np.array([5,4,3,7])
A[2:]

array([3, 7])

In [14]:
dic = {"A": 1, "B":2}
for i,j in enumerate(dic):
  print(i,j)

0 A
1 B


In [15]:
l1 = [3,4,5]
l2 = [5,6,7]
for i,j in zip(l1,l2):
  print(i,j)

3 5
4 6
5 7


In [16]:
a = [2,5,6]
y = [i**2 for i in a]
print(y)

[4, 25, 36]


In [17]:
b = np.array(a)
print(b*b)

[ 4 25 36]


The interest, i, on a principle, $P_0$, is a payment for allowing the bank to use your money. Compound interest is accumulated according to the formula $P_n=(1+i)P_{n−1}$, where n is the compounding period, usually in months or years. Write a function my_saving_plan$(P_0, i, goal)$ where the output is the number of years it will take $P_0$ to become goal at $i\%$ interest compounded annually.

In [20]:
"""
Q4
The interest, i, on a principle, P0, is a payment for allowing the bank to use your money. 
Compound interest is accumulated according to the formula Pn=(1+i)Pn−1, where n is the compounding period, 
usually in months or years. Write a function my_saving_plan(P0, i, goal) 
where the output is the number of years it will take P0 to become goal at i% interest compounded annually.
"""
def my_saving_plan(p0,i,goal):
  p = p0
  c=1
  while(c>0):
    p = (1+i)*p
    if(p>=goal):
      break
    c +=1
  return c

In [22]:
# Output: 15
my_saving_plan(1000, 0.05, 2000)

15